quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/java-with-quarkus-data-base
    db-kind: postgresql
    username: postgres
    password: _JavaQuarkus
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    auth:
      proactive: false

mp:
  jwt:
    verify:
      publickey:
        location: /jwt/publicKey.pem
      issuer: https://example.com/issuer

smallrye:
  jwt:
    sign:
      key:
        location: /jwt/privateKey.pem
